<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Unit;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('email', 'admin@example.com')->first();
        $categories = Category::all();
        $brands = Brand::all();
        $units = Unit::all();

        $products = [
            // Electronics
            [
                'name' => 'iPhone 14 Pro Max',
                'sku' => 'SKU-IP14PM-001',
                'barcode' => '890123456789',
                'description' => 'Latest iPhone with A16 chip, 48MP camera, and Dynamic Island',
                'category_id' => $categories->where('name', 'Smartphones & Tablets')->first()->id,
                'brand_id' => $brands->where('name', 'Apple')->first()->id,
                'unit_id' => $units->where('short_name', 'pc')->first()->id,
                'purchase_price' => 999.00,
                'selling_price' => 1199.00,
                'wholesale_price' => 1099.00,
                'min_price' => 1099.00,
                'max_price' => 1299.00,
                'tax_rate' => 8.00,
                'tax_type' => 'exclusive',
                'discount_type' => 'percentage',
                'discount_value' => 5.00,
                'stock_quantity' => 50,
                'low_stock_threshold' => 10,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Samsung Galaxy S23 Ultra',
                'sku' => 'SKU-SGS23-001',
                'barcode' => '890123456790',
                'description' => 'Samsung flagship with 200MP camera and S Pen',
                'category_id' => $categories->where('name', 'Smartphones & Tablets')->first()->id,
                'brand_id' => $brands->where('name', 'Samsung')->first()->id,
                'unit_id' => $units->where('short_name', 'pc')->first()->id,
                'purchase_price' => 899.00,
                'selling_price' => 1099.00,
                'wholesale_price' => 999.00,
                'min_price' => 999.00,
                'max_price' => 1199.00,
                'tax_rate' => 8.00,
                'tax_type' => 'exclusive',
                'discount_type' => 'fixed',
                'discount_value' => 50.00,
                'stock_quantity' => 45,
                'low_stock_threshold' => 8,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'MacBook Pro 16" M2',
                'sku' => 'SKU-MBP16-001',
                'barcode' => '890123456791',
                'description' => 'Apple MacBook Pro with M2 Pro chip, 16GB RAM, 512GB SSD',
                'category_id' => $categories->where('name', 'Computers & Laptops')->first()->id,
                'brand_id' => $brands->where('name', 'Apple')->first()->id,
                'unit_id' => $units->where('short_name', 'pc')->first()->id,
                'purchase_price' => 1899.00,
                'selling_price' => 2299.00,
                'wholesale_price' => 2099.00,
                'min_price' => 2099.00,
                'max_price' => 2499.00,
                'tax_rate' => 8.00,
                'tax_type' => 'exclusive',
                'discount_type' => 'fixed',
                'discount_value' => 100.00,
                'stock_quantity' => 25,
                'low_stock_threshold' => 5,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Dell XPS 15',
                'sku' => 'SKU-DXPS15-001',
                'barcode' => '890123456792',
                'description' => 'Dell XPS 15 with Intel i9, 32GB RAM, 1TB SSD, RTX 3050',
                'category_id' => $categories->where('name', 'Computers & Laptops')->first()->id,
                'brand_id' => $brands->where('name', 'Dell')->first()->id,
                'unit_id' => $units->where('short_name', 'pc')->first()->id,
                'purchase_price' => 1699.00,
                'selling_price' => 1999.00,
                'wholesale_price' => 1899.00,
                'min_price' => 1899.00,
                'max_price' => 2199.00,
                'tax_rate' => 8.00,
                'tax_type' => 'exclusive',
                'discount_type' => 'percentage',
                'discount_value' => 10.00,
                'stock_quantity' => 30,
                'low_stock_threshold' => 5,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => false,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Sony WH-1000XM5',
                'sku' => 'SKU-SONYWH5-001',
                'barcode' => '890123456793',
                'description' => 'Sony flagship noise-cancelling headphones',
                'category_id' => $categories->where('name', 'Audio & Headphones')->first()->id,
                'brand_id' => $brands->where('name', 'Sony')->first()->id,
                'unit_id' => $units->where('short_name', 'pc')->first()->id,
                'purchase_price' => 299.00,
                'selling_price' => 399.00,
                'wholesale_price' => 349.00,
                'min_price' => 349.00,
                'max_price' => 429.00,
                'tax_rate' => 8.00,
                'tax_type' => 'exclusive',
                'discount_type' => 'percentage',
                'discount_value' => 15.00,
                'stock_quantity' => 100,
                'low_stock_threshold' => 20,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Canon EOS R6 Mark II',
                'sku' => 'SKU-CANR6-001',
                'barcode' => '890123456794',
                'description' => 'Canon mirrorless camera with 24.2MP sensor and 4K video',
                'category_id' => $categories->where('name', 'Cameras & Photography')->first()->id,
                'brand_id' => $brands->where('name', 'Canon')->first()->id,
                'unit_id' => $units->where('short_name', 'pc')->first()->id,
                'purchase_price' => 1999.00,
                'selling_price' => 2499.00,
                'wholesale_price' => 2299.00,
                'min_price' => 2299.00,
                'max_price' => 2699.00,
                'tax_rate' => 8.00,
                'tax_type' => 'exclusive',
                'discount_type' => null,
                'discount_value' => 0,
                'stock_quantity' => 15,
                'low_stock_threshold' => 3,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => false,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'LG 65" C3 OLED TV',
                'sku' => 'SKU-LG65C3-001',
                'barcode' => '890123456795',
                'description' => 'LG C3 65-inch 4K Smart OLED TV with α9 Gen6 processor',
                'category_id' => $categories->where('name', 'TV & Home Theater')->first()->id,
                'brand_id' => $brands->where('name', 'LG')->first()->id,
                'unit_id' => $units->where('short_name', 'pc')->first()->id,
                'purchase_price' => 1599.00,
                'selling_price' => 1899.00,
                'wholesale_price' => 1799.00,
                'min_price' => 1799.00,
                'max_price' => 2099.00,
                'tax_rate' => 8.00,
                'tax_type' => 'exclusive',
                'discount_type' => 'fixed',
                'discount_value' => 200.00,
                'stock_quantity' => 20,
                'low_stock_threshold' => 4,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Sony PlayStation 5',
                'sku' => 'SKU-PS5-001',
                'barcode' => '890123456796',
                'description' => 'PlayStation 5 console with DualSense controller',
                'category_id' => $categories->where('name', 'Gaming')->first()->id,
                'brand_id' => $brands->where('name', 'Sony')->first()->id,
                'unit_id' => $units->where('short_name', 'pc')->first()->id,
                'purchase_price' => 399.00,
                'selling_price' => 499.00,
                'wholesale_price' => 459.00,
                'min_price' => 459.00,
                'max_price' => 549.00,
                'tax_rate' => 8.00,
                'tax_type' => 'exclusive',
                'discount_type' => 'percentage',
                'discount_value' => 5.00,
                'stock_quantity' => 40,
                'low_stock_threshold' => 10,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Apple Watch Series 8',
                'sku' => 'SKU-AW8-001',
                'barcode' => '890123456797',
                'description' => 'Apple Watch Series 8 with temperature sensing and crash detection',
                'category_id' => $categories->where('name', 'Wearable Technology')->first()->id,
                'brand_id' => $brands->where('name', 'Apple')->first()->id,
                'unit_id' => $units->where('short_name', 'pc')->first()->id,
                'purchase_price' => 329.00,
                'selling_price' => 399.00,
                'wholesale_price' => 369.00,
                'min_price' => 369.00,
                'max_price' => 429.00,
                'tax_rate' => 8.00,
                'tax_type' => 'exclusive',
                'discount_type' => 'percentage',
                'discount_value' => 10.00,
                'stock_quantity' => 60,
                'low_stock_threshold' => 15,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Logitech MX Master 3S',
                'sku' => 'SKU-LOGMX3S-001',
                'barcode' => '890123456798',
                'description' => 'Logitech MX Master 3S wireless mouse',
                'category_id' => $categories->where('name', 'Computers & Laptops')->first()->id,
                'brand_id' => $brands->where('name', 'Logitech')->first()->id,
                'unit_id' => $units->where('short_name', 'pc')->first()->id,
                'purchase_price' => 69.00,
                'selling_price' => 99.00,
                'wholesale_price' => 89.00,
                'min_price' => 89.00,
                'max_price' => 109.00,
                'tax_rate' => 8.00,
                'tax_type' => 'exclusive',
                'discount_type' => 'fixed',
                'discount_value' => 10.00,
                'stock_quantity' => 150,
                'low_stock_threshold' => 30,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => false,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'Nike Air Max 270',
                'sku' => 'SKU-NKAM270-001',
                'barcode' => '890123456799',
                'description' => 'Nike Air Max 270 sneakers - Men\'s size 9',
                'category_id' => $categories->where('name', 'Clothing & Apparel')->first()->id,
                'brand_id' => $brands->where('name', 'Nike')->first()->id,
                'unit_id' => $units->where('short_name', 'pr')->first()->id,
                'purchase_price' => 89.00,
                'selling_price' => 150.00,
                'wholesale_price' => 130.00,
                'min_price' => 130.00,
                'max_price' => 170.00,
                'tax_rate' => 6.00,
                'tax_type' => 'exclusive',
                'discount_type' => 'percentage',
                'discount_value' => 20.00,
                'stock_quantity' => 200,
                'low_stock_threshold' => 40,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => true,
                'created_by' => $admin->id,
            ],
            [
                'name' => 'LEGO Star Wars Millennium Falcon',
                'sku' => 'SKU-LG75192-001',
                'barcode' => '890123456800',
                'description' => 'LEGO Star Wars Millennium Falcon 75192 - Ultimate Collector Series',
                'category_id' => $categories->where('name', 'Toys & Games')->first()->id,
                'brand_id' => $brands->where('name', 'LEGO')->first()->id,
                'unit_id' => $units->where('short_name', 'box')->first()->id,
                'purchase_price' => 599.00,
                'selling_price' => 849.00,
                'wholesale_price' => 749.00,
                'min_price' => 749.00,
                'max_price' => 899.00,
                'tax_rate' => 6.00,
                'tax_type' => 'exclusive',
                'discount_type' => 'fixed',
                'discount_value' => 50.00,
                'stock_quantity' => 10,
                'low_stock_threshold' => 2,
                'allow_out_of_stock' => false,
                'is_active' => true,
                'is_featured' => true,
                'created_by' => $admin->id,
            ],
        ];

        foreach ($products as $product) {
            $product['slug'] = Str::slug($product['name']);
            $product['discount_amount'] = $product['discount_type'] === 'percentage' 
                ? ($product['selling_price'] * $product['discount_value'] / 100)
                : $product['discount_value'];
            
            Product::create($product);
        }

        
    }
}